blank_issues_enabled: true
contact_links:
  - name: 📚 Documentation
    url: https://docs.rs/py-import-helper
    about: Check the full API documentation on docs.rs
  - name: 💬 Discussions
    url: https://github.com/timrabl/rs-py-import-helper/discussions
    about: Ask questions or share ideas
