globs:
  - "**/*.md"

config:
  MD001: true
  MD003: true
  MD004: true
  MD005: true
  MD007: true
  MD009: true
  MD010: true
  MD011: true
  MD012: true
  MD013: true
  MD014: true
  MD018: true
  MD019: true
  MD020: true
  MD021: true
  MD022: true
  MD023: true
  MD024: true
  MD025: true
  MD026: true
  MD027: true
  MD028: true
  MD029: true
  MD030: true
  MD031: true
  MD032: true
  MD033: true
  MD034: true
  MD035: true
  MD036: true
  MD037: true
  MD038: true
  MD039: true
  MD040: true
  MD041: true
  MD042: true
  MD043: true
  MD044: true
  MD045: true
  MD046: true
  MD047: true
  MD048: true
  MD049: true
  MD050: true
  MD051: true
  MD052: true
  MD053: true
  MD054: true
  MD055: true
  MD056: true
  MD058: true
  MD059: true
  accessibility: true
  atx: true
  atx_closed: true
  blank_lines: true
  blanks-around-fences: true
  blanks-around-headings: true
  blanks-around-lists: true
  blanks-around-tables: true
  blockquote: true
  bullet: true
  code-block-style: true
  code-fence-style: true
  code: true
  commands-show-output: true
  default: true
  descriptive-link-text: true
  emphasis-style: true
  emphasis: true
  extends: "null"
  fenced-code-language: true
  first-line-h1: true
  first-line-heading: true
  hard_tab: true
  heading-increment: true
  heading-start-left: true
  heading-style: true
  headings: true
  hr-style: true
  hr: true
  html: true
  images: true
  indentation: true
  language: true
  line-length: true
  line_length: true
  link-fragments: true
  link-image-reference-definitions: true
  link-image-style: true
  links: true
  list-indent: true
  list-marker-space: true
  no-alt-text: true
  no-bare-urls: true
  no-blanks-blockquote: true
  no-duplicate-heading: true
  no-emphasis-as-heading: true
  no-empty-links: true
  no-hard-tabs: true
  no-inline-html: true
  no-missing-space-atx: true
  no-missing-space-closed-atx: true
  no-multiple-blanks: true
  no-multiple-space-atx: true
  no-multiple-space-blockquote: true
  no-multiple-space-closed-atx: true
  no-reversed-links: true
  no-space-in-code: true
  no-space-in-emphasis: true
  no-space-in-links: true
  no-trailing-punctuation: true
  no-trailing-spaces: true
  ol-prefix: true
  ol: true
  proper-names: true
  reference-links-images: true
  required-headings: true
  single-h1: true
  single-title: true
  single-trailing-newline: true
  spaces: true
  spelling: true
  strong-style: true
  table-column-count: true
  table-pipe-style: true
  table: true
  ul-indent: true
  ul-style: true
  ul: true
  url: true
  whitespace: true

ignores:
  - node_modules/**
  - .venv/**
  - venv/**
  - .git/**
  - dist/**
  - build/**
  - __pycache__/**
  - .pytest_cache/**
  - .mypy_cache/**
  - .ruff_cache/**
  - .idea/**
  - .vscode/**
  - "*.egg-info/**"
  - .tox/**
  - coverage/**
  - htmlcov/**
  - .coverage
  - .nyc_output/**
  - .env
  - .env.local
  - .env.*.local
