name: Security Audit

on:
    schedule:
        # Run every Monday at 9 AM Berlin time
        - cron: "0 9 * * 1"
    workflow_dispatch:
    push:
        paths:
            - "**/Cargo.toml"
            - "**/Cargo.lock"

env:
    CARGO_TERM_COLOR: always

jobs:
    security-audit:
        name: Security Audit
        runs-on: ubuntu-latest
        permissions:
            contents: read
            issues: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@stable
            - name: Install cargo-audit
              run: cargo install --force cargo-audit
            - name: Run security audit
              run: cargo audit --json > audit-results.json
            - name: Upload audit results
              uses: actions/upload-artifact@v5
              if: always()
              with:
                  name: security-audit-results
                  path: audit-results.json
            - name: Check for vulnerabilities
              run: |
                  if cargo audit --deny warnings; then
                    echo "✅ No security vulnerabilities found"
                  else
                    echo "❌ Security vulnerabilities detected"
                    cargo audit
                    exit 1
                  fi
