name: Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_call:

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@4360b52568e2003a75bf9bc1d59f33a8e3fc893c # stable branch
            - name: Run tests
              run: cargo test --all-features

    clippy:
        name: Clippy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@4360b52568e2003a75bf9bc1d59f33a8e3fc893c # stable branch
              with:
                  components: clippy
            - name: Run clippy
              run: cargo clippy --all-targets --all-features -- -D warnings

    fmt:
        name: Rustfmt
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@4360b52568e2003a75bf9bc1d59f33a8e3fc893c # stable branch
              with:
                  components: rustfmt
            - name: Run rustfmt
              run: cargo fmt --all -- --check

    docs:
        name: Docs
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@4360b52568e2003a75bf9bc1d59f33a8e3fc893c # stable branch
            - name: Check documentation
              run: cargo doc --all-features --no-deps

    benchmarks:
        name: Benchmarks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@4360b52568e2003a75bf9bc1d59f33a8e3fc893c # stable branch
            - name: Run benchmarks
              run: cargo bench --bench benchmarks
            - name: Upload benchmark results
              uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
              with:
                  name: benchmark-results
                  path: target/criterion/
